{{- $fullName := print (include "ztv-anmeldetool.fullname" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}-backend-db-secret 
  namespace: ztv
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: {{ .Values.backend.database.username | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.backend.database.password | quote }}
