{{- $fullName := print (include "ztv-anmeldetool.fullname" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}-backend-mail-secret 
  namespace: ztv
type: Opaque
stringData:
  MAIL_ENABLED: {{ .Values.backend.mail.enabled | quote }}
  MAIL_USER: {{ .Values.backend.mail.username | quote }}
  MAIL_PASSWORD: {{ .Values.backend.mail.password | quote }}
  MAIL_HOST: {{ .Values.backend.mail.host | quote }}
  MAIL_PORT: {{.Values.backend.mail.port | quote }}

