server:
  port: 8080
  servlet:
    context-path: /
spring:
  profiles:
    active: "prod"
  flyway:
    locations: ["classpath:/db/migration"]
    clean-on-validation-error: true
    username: postgres
    password: getu@ztv

  jpa:
     database-platform: org.hibernate.dialect.PostgreSQLDialect
     show-sql: "false"
     properties:
        hibernate:
           jdbc:
              time_zone: "GMT+1"
              
  datasource:
    url: jdbc:postgresql://db:5432/getuwettkaempfe
    username: postgres
    password: getu@ztv
  jackson:
     deserialization:
        adjust-dates-to-context-time-zone: true
     time-zone: "Europe/Zurich"   
     # time-zone: "UTC"
# this info may be accessed via actuator
info:
  app:
    name: Anmeldetool
    version: "@version@"
    buildtime: "@timestamp@"

logging:
  level:
    org.springframework.cloud: INFO
    org.springframework.security: INFO
    org.flywaydb: INFO
    org.springframework.web.cors: INFO
    org.hibernate.SQL: INFO

management:
  endpoints:
    web:
      cors:
        path-mappings: /**
        allowed-origins: ${CORS_ALLOWED_ORIGINS}
        allowed-methods: GET, POST, PUT
        allowed-headers: "*"
  server:
    servlet:
      context-path: /admin
  endpoint:
    beans:
      enabled: true
    health:
      enabled: true
    info:
      enabled: true