spring:
  flyway:
    locations: ["classpath:/db/migration"]
    clean-on-validation-error: true
    username: postgres
    password: adrian2000
  jpa:
     database-platform: org.hibernate.dialect.PostgreSQLDialect
     show-sql: "false"
     
  datasource:
    url: jdbc:postgresql://localhost:5432/getu-wettkaempfe
    username: postgres
    password: adrian2000

logging:
  level:
    root: warn
    org:
      ztv: debug

management:
  endpoints:
    web:
      cors:
        allowed-origins: http://localhost:4200
