spring.datasource.username=postgres
spring.datasource.password=getu@ztv
spring.flyway.username=postgres
spring.flyway.password=getu@ztv
spring.mail.username=getu-wettkaempfe-tu@ztv.ch
spring.mail.password=Cav67716

