spring.datasource.username=postgres
spring.datasource.password=secret
spring.flyway.username=postgres
spring.flyway.password=secret
spring.mail.username=getu-wettkaempfe-tu@ztv.ch
spring.mail.password=secret

