INSERT INTO VERBAND (ID, AKTIV, DELETED, VERBAND, VERBAND_LONG) VALUES (RANDOM_UUID(), '1', '0', 'STV', 'Schweizer Turnverband');
INSERT INTO VERBAND (ID, AKTIV, DELETED, VERBAND, VERBAND_LONG) VALUES (RANDOM_UUID(), '1', '0', 'ZTV', 'Zürcher Turnverband');
INSERT INTO VERBAND (ID, AKTIV, DELETED, VERBAND, VERBAND_LONG) VALUES (RANDOM_UUID(), '1', '0', 'GLZ', 'Region Glatt- Limmattal und Stadt Zürich');
INSERT INTO VERBAND (ID, AKTIV, DELETED, VERBAND, VERBAND_LONG) VALUES (RANDOM_UUID(), '1', '0', 'WTU', 'Region Winterthur und Umgebung');
INSERT INTO VERBAND (ID, AKTIV, DELETED, VERBAND, VERBAND_LONG) VALUES (RANDOM_UUID(), '1', '0', 'AZO', 'Region Albis, Zürichsee und Oberland');
INSERT INTO VERBAND (ID, AKTIV, DELETED, VERBAND, VERBAND_LONG) VALUES (RANDOM_UUID(), '1', '0', 'UTV', 'Urner Turnverband');
INSERT INTO VERBAND (ID, AKTIV, DELETED, VERBAND, VERBAND_LONG) VALUES (RANDOM_UUID(), '1', '0', 'GRTV', 'Graubündner Turnverband');
