ALTER TABLE TEILNEHMER_ANLASS_LINK ADD STARTNUMMER INTEGER;
ALTER TABLE TEILNEHMER_ANLASS_LINK ADD ABTEILUNG VARCHAR(10);
ALTER TABLE TEILNEHMER_ANLASS_LINK ADD ANLAGE VARCHAR(10);
ALTER TABLE TEILNEHMER_ANLASS_LINK ADD STARTGERAET varchar(100);

ALTER TABLE TEILNEHMER_ANLASS_LINK ADD CONSTRAINT UNIQUE_ANLASS_STARTNUMMER UNIQUE (ANLASS_ID, STARTNUMMER);