create table NOTENBLATT
(
    ID            uuid          default  gen_random_uuid(),
    AKTIV         BOOLEAN,
    DELETED       BOOLEAN,
    CHANGE_DATE   TIMESTAMP(6),
    DELETION_DATE TIMESTAMP(6),
 
    TEILNEHMER_ANLASS_LINK_ID    	uuid,
    GESAMT_PUNKTZAHL	decimal(5,3),
    RANG			integer,
    AUSZEICHNUNG	BOOLEAN,
 	ERFASST		 	BOOLEAN,
 	CHECKED		 	BOOLEAN,
   
    PRIMARY KEY (ID)
);


CREATE UNIQUE INDEX uidx_NOTENBLATT ON NOTENBLATT (ID);

CREATE INDEX idx_NOTENBLATT_DELETED ON NOTENBLATT (DELETED);

CREATE INDEX idx_NOTENBLATT_TEILNEHMER_ANLASS_LINK_ID ON NOTENBLATT (TEILNEHMER_ANLASS_LINK_ID);

CREATE INDEX idx_NOTENBLATT_ERFASST ON NOTENBLATT (ERFASST);

CREATE INDEX idx_NOTENBLATT_CHECKED ON NOTENBLATT (CHECKED);

create table EINZELNOTE
(
    ID            	uuid          default  gen_random_uuid(),
    AKTIV         	BOOLEAN,
    DELETED       	BOOLEAN,
    CHANGE_DATE   	TIMESTAMP(6),
    DELETION_DATE 	TIMESTAMP(6),
 
    NOTENBLATT_ID   uuid,
    LAUFLISTEN_ID   uuid,
    GERAET 			varchar(100),
	START_ORDER		INTEGER,

 	ERFASST		 	BOOLEAN default false,
 	CHECKED		 	BOOLEAN default false,

    NOTE_1			decimal(5,3),
    NOTE_2			decimal(5,3),
    ZAEHLBAR		decimal(5,3),
   
    PRIMARY KEY (ID)
);


CREATE UNIQUE INDEX uidx_EINZELNOTE ON EINZELNOTE (ID);

CREATE INDEX idx_EINZELNOTE_ERFASST ON EINZELNOTE (ERFASST);

CREATE INDEX idx_EINZELNOTE_CHECKED ON EINZELNOTE (CHECKED);

CREATE INDEX idx_EINZELNOTE_DELETED ON EINZELNOTE (DELETED);

create table RANGLISTEN_CONFIGURATION
(
    ID            	uuid          default  gen_random_uuid(),
    AKTIV         	BOOLEAN,
    DELETED       	BOOLEAN,
    CHANGE_DATE   	TIMESTAMP(6),
    DELETION_DATE 	TIMESTAMP(6),
 
    ANLASS_ID   	uuid,
    KATEGORIE		VARCHAR(2),
	TI_TU			VARCHAR(4),
	
	MAX_AUSZEICHNUNGEN	integer,
   
    PRIMARY KEY (ID)
);


CREATE UNIQUE INDEX uidx_RANGLISTEN_CONFIGURATION ON RANGLISTEN_CONFIGURATION (ID);

CREATE INDEX idx_RANGLISTEN_CONFIGURATION_ANLASS_ID ON RANGLISTEN_CONFIGURATION (ANLASS_ID);

CREATE INDEX idx_RANGLISTEN_CONFIGURATION_DELETED ON RANGLISTEN_CONFIGURATION (DELETED);

ALTER TABLE TEILNEHMER_ANLASS_LINK ADD NOTENBLATT_ID uuid;

ALTER TABLE LAUFLISTE ADD ABLOESUNG integer;

ALTER TABLE ANLASS DROP ORGANISATOR;
   
ALTER TABLE ANLASS ADD ORGANISATOR_ID uuid;

CREATE INDEX idx_ANLASS ON ANLASS (ORGANISATOR_ID);

ALTER TABLE ROLLE ADD PUBLIC_ASSIGNABLE BOOLEAN default true;
