create table LAUFLISTEN_CONTAINER
(
    ID            uuid          default  gen_random_uuid(),
    AKTIV         BOOLEAN,
    DELETED       BOOLEAN,
    CHANGE_DATE   TIMESTAMP(6),
    DELETION_DATE TIMESTAMP(6),
 
    ANLASS_ID    	uuid,
    KEY				integer,
 	ERFASST		 	BOOLEAN,
 	CHECKED		 	BOOLEAN,
 	KATEGORIE		VARCHAR(2),
 	STARTGERAET		integer,
   
    PRIMARY KEY (ID)
);


CREATE UNIQUE INDEX uidx_LAUFLISTEN_CONTAINER ON LAUFLISTEN_CONTAINER (ID);

CREATE INDEX idx_LAUFLISTEN_CONTAINER_DELETED ON LAUFLISTEN_CONTAINER (DELETED);

CREATE INDEX idx_LAUFLISTEN_CONTAINER_ANLASS_ID ON LAUFLISTEN_CONTAINER (ANLASS_ID);

create table LAUFLISTE
(
    ID            uuid          default  gen_random_uuid(),
    AKTIV         BOOLEAN,
    DELETED       BOOLEAN,
    CHANGE_DATE   TIMESTAMP(6),
    DELETION_DATE TIMESTAMP(6),
 
    KEY				VARCHAR(5),
    LAUFLISTEN_CONTAINER_ID    	uuid,
    GERAET 			varchar(100),

 	ERFASST		 	BOOLEAN,
 	CHECKED		 	BOOLEAN,
   
    PRIMARY KEY (ID)
);


CREATE UNIQUE INDEX uidx_LAUFLISTE ON LAUFLISTE (ID);

CREATE INDEX idx_LAUFLISTE_KEY ON LAUFLISTE (KEY);

CREATE INDEX idx_LAUFLISTE_ERFASST ON LAUFLISTE (ERFASST);

CREATE INDEX idx_LAUFLISTE_CHECKED ON LAUFLISTE (CHECKED);

CREATE INDEX idx_LAUFLISTE_DELETED ON LAUFLISTE (DELETED);


ALTER TABLE TEILNEHMER_ANLASS_LINK ADD LAUFLISTEN_CONTAINER_ID uuid;
